# source generated by foxGUIb 0.7.1

class Loader
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@mainWindow=w
			w.wdg_name='mainWindow'
			w.width=461
			w.shown=true
			w.y=290
			w.height=415
			w.x=211
			FX::VerticalFrame.new(@mainWindow){|w|
				@verticalframe1=w
				w.wdg_name='verticalframe1'
				w.width=461
				w.height=415
				FX::HorizontalFrame.new(@verticalframe1){|w|
					@horizontalframe1=w
					w.wdg_name='horizontalframe1'
					w.width=461
					w.height=301
					FX::Button.new(@horizontalframe1){|w|
						@runButton=w
						w.wdg_name='runButton'
						w.text="     Run      "
						w.width=60
						w.height=21
						@runButton.connect(Fox::SEL_COMMAND){
							run_process
						}
					}
					FX::VerticalFrame.new(@horizontalframe1){|w|
						@verticalframe4=w
						w.wdg_name='verticalframe4'
						w.width=273
						w.height=301
						w.x=60
						FX::Label.new(@verticalframe4){|w|
							@label6=w
							w.wdg_name='label6'
							w.text="Dataset"
							w.width=42
							w.height=17
						}
						FX::RadioMutex.new(@verticalframe4){|w|
							@radiomutex1=w
							w.wdg_name='radiomutex1'
							w.width=125
							w.y=17
							w.height=102
							FX::RadioButton.new(@radiomutex1){|w|
								@labor=w
								w.wdg_name='labor'
								w.text="Labor Negotiation"
								w.width=106
								w.height=17
								w.state=true
							}
							FX::RadioButton.new(@radiomutex1){|w|
								@iris=w
								w.wdg_name='iris'
								w.text="Iris Plants"
								w.width=68
								w.y=17
								w.height=17
							}
							FX::RadioButton.new(@radiomutex1){|w|
								@soybean=w
								w.wdg_name='soybean'
								w.text="Soybean"
								w.width=63
								w.y=34
								w.height=17
							}
							FX::RadioButton.new(@radiomutex1){|w|
								@tennis=w
								w.wdg_name='tennis'
								w.text="Tennis Playing"
								w.width=89
								w.y=51
								w.height=17
							}
							FX::RadioButton.new(@radiomutex1){|w|
								@fitting=w
								w.wdg_name='fitting'
								w.text="Fitting Contact lenses"
								w.width=125
								w.y=68
								w.height=17
							}
							FX::RadioButton.new(@radiomutex1){|w|
								@other=w
								w.wdg_name='other'
								w.text="Other"
								w.width=49
								w.y=85
								w.height=17
							}
						}
						FX::TextField.new(@verticalframe4){|w|
							@textfield2=w
							w.wdg_name='textfield2'
							w.width=66
							w.y=119
							w.height=19
							w.numColumns=10
						}
					}
					FX::VerticalFrame.new(@horizontalframe1){|w|
						@verticalframe5=w
						w.wdg_name='verticalframe5'
						w.width=64
						w.height=301
						w.x=333
						FX::Label.new(@verticalframe5){|w|
							@label7=w
							w.wdg_name='label7'
							w.width=29
							w.height=17
						}
					}
					FX::VerticalFrame.new(@horizontalframe1){|w|
						@verticalframe6=w
						w.wdg_name='verticalframe6'
						w.width=64
						w.height=301
						w.x=397
						FX::Label.new(@verticalframe6){|w|
							@label8=w
							w.wdg_name='label8'
							w.width=29
							w.height=17
						}
					}
				}
				FX::Text.new(@verticalframe1){|w|
					@resultTextArea=w
					w.wdg_name='resultTextArea'
					w.width=461
					w.y=301
					w.height=114
				}
			}
		}
	end
  
  def run_process
#    if resultTextArea.text!= nil
#    in_file = filename.text + '.arff' #ARGV[0]
#    contents = ''
#    contents = File.open(in_file).read
#    rel = Rarff::Relation.new
#    rel.parse(contents)
#    
#    else
#      resultTextArea.text='enter file name'
#    end
#    header= '='*80 +"\nARFF:"
    #puts rel
#    resultTextArea.text= 
    puts radiomutex1.value
  end
	attr_reader :topwin
	attr_reader :mainWindow
	attr_reader :verticalframe1
	attr_reader :horizontalframe1
	attr_reader :runButton
	attr_reader :verticalframe4
	attr_reader :label6
	attr_reader :radiomutex1
	attr_reader :labor
	attr_reader :iris
	attr_reader :soybean
	attr_reader :tennis
	attr_reader :fitting
	attr_reader :other
	attr_reader :textfield2
	attr_reader :verticalframe5
	attr_reader :label7
	attr_reader :verticalframe6
	attr_reader :label8
	attr_reader :resultTextArea
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=Loader.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
